name: Release to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger when a tag matching v*.*.* is pushed (e.g., v0.0.4)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Or your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Extract version from Git tag
        id: extract_version
        run: |
          VERSION=$(echo ${GITHUB_REF} | sed 's/refs\/tags\/v//')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Extracted version: ${VERSION}"

      - name: Update pyproject.toml version dynamically
        run: |
          sed "s|%version%|${{ env.VERSION }}|g;" pyproject.toml
          cat pyproject.toml

      - name: Build the package
        run: |
          python -m build

      - name: Publish to PyPI
        run: |
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__   # Use this value for authentication
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # Use the token from GitHub secrets
