name: Release to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger when a tag matching v*.*.* is pushed (e.g., v0.0.4)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Or your preferred Python version          

      - name: Update PyPi version dynamically based on git tag
        id: update_version
        run: |
          # Install build and twine dependencies
          python -m pip install --upgrade pip
          pip install build twine
        
          # Extract version
          VERSION=$(echo ${GITHUB_REF} | sed 's/refs\/tags\/v//')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Extracted version: ${VERSION}"

          # Update toml file
          sed "s|%version%|${{ env.VERSION }}|g;" pyproject.toml
          cat pyproject.toml

          # Build the package
          python -m build

          # Publish to PyPi
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__   # Use this value for authentication
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # Use the token from GitHub secrets
